# Generated by Django 3.2.2 on 2021-05-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0002_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_id', models.IntegerField()),
                ('booking_time', models.CharField(max_length=100)),
            ],
        ),
    ]
